const content = {
    uz: {

        // Header
        add: "E'lon Qo'shish",
        fromBtn: "Kirish",
        placeTooltip: "Joylashuvingiz",
        langTooltip: "Tilni almashtirish",
        loveTooltip: "Sizning Yoqtirganlaringiz",
        currencyTooltip: "Valyutani almashtirish",

        // Navbar
        sal: "Sotuv",
        rent: "Ijara",
        rel: "Reltorlar",
        mor: "Yana",

        // Hero
        hero_title: "Toping. Sayohat qiling. Egalik qiling.",
        hero_search: "Qidirish",

        // Main
        nearHomes: "Yaqin atrofdagi uylar",
        populr_title: "Ommabob Uylar",
        new_title: "Yangi Binolar",
        see_desc: "Barchasini ko’rish",
        reltor_aside_title: "Reltorlar",
        error_desc: "Ma'lumotlar olishda xatolik yuz berdi",

        // Footer
        footer_text: "Masofaviy Uy oldi sotdisi bo'yicha Milliy platforma",
        users_title: "Foydalanuvchilarga",
        contact_us: "Biz bilan aloqa",
        social_networks: "Biz ijtimoiy tarmoqlarda",

        // Bilmadim bu nimaligni lekin
        we: "Biz haqimizda",
        why_afeme_title: "Nima uchun Afeme ?",
        why_afeme_bot: "AFEME BOTI VA KANALI",
        why_afeme_botdesc: "Telegram bot va kanalimizni ishlatib koʻring",

        // Form Modal
        form_modal_title: "Saytga kirish",
        from_modal_inputtel: "Telfon Raqam",
        from_modal_btnsubmit: "Kirish",
        from_sign: "Ro'yxatdan o'tish",
        help: 'Yordam',

        // Form Page
        form_select_jis: "Jismoniy shaxs",
        form_select_vil: "Viloyat",
        from_select_nam: "Ism",
        form_select_nam_req: "Ism kiriting",
        form_select_las: "Familiya",
        form_select_las_req: "Familiya kiting",
        form_select_email: "Email",
        form_select_email_req: "Email manzili kiriting",
        form_select_email_err: "Email manzili noto‘g‘ri",
        form_select_pas: "Passport",
        form_select_tel: "Telefon raqam",
        form_select_tel_req: "Telefon raqami kiriting",
        form_myaccount: "Mening hisobim bor",
        form_select_type_sh: 'Shaxsiy',
        form_select_type_b: 'Biznez',
        rexperience: 'Tajriba',
        bio: 'Malumot',
        have: 'Mening Akkauntim bor',
        sing: 'Royhatdan otish',
        submit: 'Tasdiqlash',

        // Reltos Page
        reltor_title: "Rieltorlar katalogi",
        reltor_lenght: "ta rieltor topildi",
        reltor_sort: "Filterlash",
        no_post: "Siz birorta ham E'lon joylashtirmadingiz",

        // Errors
        apiError: "Ma'lumotlar olishda xatolik yuz berdi",
        internetError: "Internet bilan aloqa Uzildi. Internet mavjud emas",

        // User Profil
        user_profil: "Mening profilim",
        user_profil_ads: "Mening eʻlonlarim",
        user_profil_message: "Mening xabarlarim",
        user_profil_favorintes: "Tanlanganlar",
        user_profil_news: "Yangiliklar",
        user_profil_clos: "Chiqish",

        //Help
        title: 'Yordam',
        title_descr: 'Biz xardoim yordam berishga tayormiz',
        name: 'Ism',
        name_error: 'Ism Kiriting',
        number: 'Telefon Raqam',
        number_error: 'Iltimos Telefon Raqamingizni Kiriting!!!',
        email: 'Email Manzili',
        email_error: 'Email Manzili Notogri',
        message_type: 'Habar Turi',
        type_taklif: 'Taqlif',
        type_shiqoyat: 'Shiqoyat',
        descr: 'Habaringizni Koldiring',
        btn: 'Yuborish',

        // AdvertPage
        advert_title: "E'lon qo'shish",
        advert_rent: "Ijara",
        adverd_sell: "Sotuv",
        adverd_mortgage: "Ipoteka",
        adverd_build_title: "Bino Turlari",
        adverd_sotish_turi: "Sotish Turlari",
        adverd_house: "Hovli",
        adverd_office: "Ofis",
        adverd_room: "Xona",
        adverd_apartment: "Kvartira",
        adverd_dala: "Dala Hovli",
        adverd_adres_office: "Ofis manzili",
        adverd_adres_city: "Shahar",
        adverd_office: "Manzil",
        adverd_house_num: "Uy Raqami",
        adverd_about_the_office: "Ofis Haqida",
        choose: 'Tanlang',
        adverd_about_1: "Qurilgan Yili:",
        adverd_about_2: "Honalar soni:",
        adverd_about_3: "Maydoni:",
        adverd_about_33: "Oshxona",
        adverd_about_34: "Xona",
        adverd_about_35: "Jami",
        adverd_about_36: "Metr Kvadrat",
        adverd_about_37: "Sotix",
        adverd_about_38: "dan:",
        adverd_about_4: "Qavat:",
        adverd_about_5: "Tamir holati:",
        adverd_about_6: "Materiallari:",
        adverd_about_evro: "Yevro",
        adverd_about_normal: "O'rtacha",
        adverd_about_tiz: "Tamir talab",
        adverd_about_gsh: "G'isht",
        adverd_about_bet: "Beton",
        adverd_about_met: "Metall",
        adverd_documents: "Ofis Chizmasi va Hujjatlari:",
        adverd_documents_dow: "Uy Hujjatlarini Yuklang",
        adverd_office_img: "Ofis rasmlari:",
        adverd_office_drop_img: "rasimni tanlang",
        adverd_office_drop_video: "videoni tanlang",
        adverd_office_video: "Ofis videolari",
        adverd_office_textior: "Uy hakida kiskacha malumot bering...",
        adverd_office_price: "Ofis narxi:",
        adverd_office_price_info: "Narxni kiriting somda",
        adverd_submit: "Elonni Yuklash",

        afemePhoneTitle: `endi har doim qo'lingizda`,
        afemePhoneDescr: 'Ilovada siz uy-joy kommunal xizmatlarini boshqarishingiz va jarayonni kuzatishingiz mumkin Biz barcha muhim narsalarni xabar qilamiz.',
        partners_title: 'Bizning hamkorlar',
        partners_descr: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laudantium ducimus in, voluptate deserunt magni fugit error atque modi iure maiores possimus nesciunt? Tempore odit ratione sunt, ut dignissimos, exercitationem a mollitia necessitatibus, aliquam asperiores neque! Quae id quod voluptate quos.',

        priceFrom: "Narxidan",
        priceTo: "Narxigacha",

        chat: "Chat",

        // Advert
        contactBtn: "Bog'lanish",
        sendMessageBtn: "Xabar yozish",
        viewInMap: "Kartadan ko'rish",
        street: "ko'chasi",
        description: "Tavsif",
        detailedView: "Batafsil ko'rish",

        //Personal
        saveBtn: 'Ozgarishlarni Saqlash',
        userProfilName: 'Ism',
        userProfilLastName: 'Familiya',
        userProfilPhone: 'Telefon Raqami',
        userProfilPassport: 'Passport',

        //SideBar
        sMenu: `Bosh sahifaga o'tish`,
        sAdd: `E'lon qo'shish`,
        sFeatures: 'Tanlanganlar',
        sHelp: 'Yordam',
        sAds: 'Mening Elonlarim',
        sLogout: 'Chiqish',

        notfound: 'Rasmlar mavjud emas',

        //Chat
        ChatNews: 'Xabarlar',
        doyou: 'Sizga yoqishi mumkin',

        liked: `Yoqtirganlarga qo'shish`,
        err: 'Muvaffaqiyatsiz !!!',
        back: 'Ortga Kaytish',
        confirm: 'borgan sms kodni kiriting !!!',
        to: 'ga',
        codeMessage: 'Sms Kodni kiring!!!',
        succ: 'Muvaffaqiyatli !!!',
        ChatNews: 'Xabarlar',
        Chat: 'Sotuvchi',
        addPic: `E'lon Rasmi`,
        doyou: 'Sizga yoqishi mumkin',

        liked: `Yoqtirganlarga qo'shish`,
        err: 'Muvaffaqiyatsiz !!!',
        back: 'Ortga Kaytish',
        confirm: 'borgan sms kodni kiriting !!!',
        to: 'ga',
        codeMessage: 'Sms Kodni kiring!!!',
        succ: 'Muvaffaqiyatli !!!',

        noResults: "Hozircha bu so'rov bo'yicha hech qanday e'lon qo'yilmagan",
        changeFilterThings: "Filterda biror narsani o'zgartirib ko'ring",
        cleanFilterThings: "Filterni tozalashga harakat qilib ko'ring",
        viaWith: "orqali qidiring",
        map: "Xarita",

        // Search
        saleType: "Sotish turi",
        homeType: "Uy turi",
        searchPlaceholder: "Manzil, shahar, viloyat, qishloq va h.k",
        clean: "Tozalash",
        viewOnMap: "Xaritadan ko'rish",
        filter: "Filter",
        forgot: 'Parolni unutdingizmi',
        forgot_title: 'Parolni tiklash',
        forgot_descr: 'Parolingizni tiklash uchun pastga emailingizni kiriting',
        forgot_error: 'Bu email manzili mavjud emas',
        forgot_title_suc: 'Muvaffaqiyatli',
        forgot_descr_suc: 'Siz kiritgan email manziliga sms habar jonatildi',
        reset_pass: 'Parolni yangilash',
        reset_pass_descr: 'Parilingizni tiklash uchun pastga emailingizni kiriting',
        form_select_pass: 'Parol',
        form_select_pass_req: 'Parol kiriting',
        form_select_code: 'CODE',
        form_select_code_req: 'Email manzilingizga yuborilgan codeni kiriting',
        forgot_reset_descr: 'Parolingiz muvaffaqiyatli ravishda ozgartirildi',

        //Post Edit
        edit_postTitle: 'Elonning tahrirlash',
        edit_post:' chi Elon',
        edit_saleType: 'Sotish Turi',
        edit_houseType: 'Uy Turi',
        edit_repairType: 'Tamir holati',
        edit_materialType: 'Qurilish Materiali',
        edit_Region: 'Viloyat',
        edit_City: 'Shaxar',
        edit_Street: 'Kocha',
        edit_House: 'Uy',
        edit_Kitchen: 'Oshona',
        edit_Living: 'Yashash',
        edit_Total: 'Umumiy',
        edit_Type: 'Turi',
        edit_M2: 'Metr Kvadrat',
        edit_AR: 'Sotix',
        edit_Date: 'Yili',
        edit_Rooms: 'Honalar',
        edit_Floor: 'Qavat',
        edit_Flat: 'Qavatligi',
        edit_Video: 'Video Qoshish',
        edit_Docs: 'Hujjat Qoshish',
        edit_Descr: 'Tavsif',
        edit_Price: 'Narhi',
        edit_Submit: 'Tasdiqlash',

        // Advert Tools
        advert_id:'Elon Raqami',
        advert_areas:'maydoni',
        advert_kitchen:'Oshxona',
        advert_living:'Yashash',
        advert_total:'Umumiy',
        advert_flat:'qavatli',
        advert_floor:'qavat',
        advert_date:'Qurilgan yili',
        advert_year:'yil',
        advert_materials:'Materiallar',
        advert_repairs:'Tamir holati',
        chat_back:'Orqaga',
    },
    en: {
        chat: "Chat",
        // Header
        add: "Add an ad",
        fromBtn: "Sign in",
        placeTooltip: "Your location",
        langTooltip: "Change language",
        loveTooltip: "Your likes",
        currencyTooltip: "Change currency",
        // Nav
        sal: "Sales",
        rent: "Rent",
        rel: "Realtors",
        mor: "More",
        // Hero
        hero_title: "Find it. Tour it. Own it.",
        hero_search: "Search",
        // Main
        nearHomes: "Nearby houses",
        populr_title: "Popular Houses",
        new_title: "New Buildings",
        see_desc: "See more",
        reltor_aside_title: "Realtors",
        // Footer
        footer_text: "National Platform for Remote Sale",
        users_title: "Users",
        contact_us: "Contact us",
        social_networks: "We are on social media",

        we: "About Us",
        why_afeme_title: "Why Afeme ?",
        why_afeme_bot: "AFEME TELEGRAM BOT AND CHANNEL",
        why_afeme_botdesc: "Try our Telegram bot and channel",

        // Form Modal
        form_modal_title: "Sign in",
        from_modal_inputtel: "Phone number",
        from_modal_btnsubmit: "Get started",
        from_sign: "Register",
        help: 'Help',

        // Form Page
        form_select_jis: "Individual",
        form_select_vil: "Province",
        from_select_nam: "Name",
        form_select_nam_req: "Enter name",
        form_select_las: "Lastname",
        form_select_las_req: "Enter lastname",
        form_select_email: "Email",
        form_select_email_req: "Enter your email address",
        form_select_email_err: "The email address is invalid",
        form_select_pas: "Passport",
        form_select_tel: "Phone number",
        form_select_tel_req: "Enter phone number",
        form_myaccount: "I have an account",
        form_select_type_sh: 'Personal',
        form_select_type_b: 'Bussines',
        rexperience: 'Experience',
        bio: 'About your self',
        have: 'I have an account',
        sing: 'SingUp',
        submit: 'Submit',

        // Reltos Page
        reltor_title: "Directory of Realtors",
        reltor_lenght: "founded this Realtors",
        reltor_sort: "Sorting",

        // User
        user_profil: "My profile",
        user_profil_message: "My Messages",
        user_profil_ads: "My listings",
        user_profil_favorintes: "Favorites",
        user_profil_news: "News",
        user_profil_clos: "Logout",

        //Help
        title: 'Help',
        title_descr: 'We are always ready to help',
        name: 'Name',
        name_error: 'Enter a name',
        number: 'Telephone Number',
        number_error: 'Enter a number',
        email: 'Email',
        email_error: 'Email address Incorrect',
        message_type: 'Message Type',
        type_taklif: 'Offer',
        type_shiqoyat: 'Complaint',
        descr: 'Leave your message',
        btn: 'Send',

        // AdvertPage
        advert_title: "Add an ad",
        advert_rent: "Rent",
        adverd_sell: "Sale",
        adverd_mortgage: "Mortgage",
        adverd_build_title: "Building Types",
        adverd_sotish_turi: "Sales Types",
        adverd_house: "Courtyard",
        adverd_office: "Office",
        adverd_room: "Room",
        adverd_apartment: "Apartment",
        adverd_dala: "Field Yard",
        adverd_adres_office: "Office address",
        adverd_adres_city: "City",
        adverd_office: "Address",
        adverd_house_num: "House number",
        adverd_about_the_office: "About the office",
        choose: 'Choose',
        adverd_about_1: "Built Year:",
        adverd_about_2: "Rooms:",
        adverd_about_3: "Area:",
        adverd_about_33: "Kitchen",
        adverd_about_34: "Room",
        adverd_about_35: "Total",
        adverd_about_36: "Meter Square",
        adverd_about_37: "Sotikh",
        adverd_about_38: "from:",
        adverd_about_4: "Floor:",
        adverd_about_5: "Repair status:",
        adverd_about_6: "Materials:",
        adverd_about_evro: "EUR",
        adverd_about_normal: "O'rtacha",
        adverd_about_tiz: "Tamir talab",
        adverd_about_gsh: "G'isht",
        adverd_about_bet: "Beton",
        adverd_about_met: "Metall",
        adverd_documents: "Office Drawings and Documents:",
        adverd_documents_dow: "Download House Documents",
        adverd_office_img: "Office pictures:",
        adverd_office_drop_img: "select a picture",
        adverd_office_drop_video: "select a video",
        adverd_office_video: "Office videos",
        adverd_office_textior: "Tell me a little about the house...",
        adverd_office_price: "Office price:",
        adverd_office_price_info: "Enter the price in sum",
        adverd_submit: "Save",

        afemePhoneTitle: `now it will always be in your hands`,
        afemePhoneDescr: 'In the app, you can manage housing utilities and monitor the process: we report all the important things.',
        partners_title: 'Our partners',
        partners_descr: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laudantium ducimus in, voluptate deserunt magni fugit error atque modi iure maiores possimus nesciunt? Tempore odit ratione sunt, ut dignissimos, exercitationem a mollitia necessitatibus, aliquam asperiores neque! Quae id quod voluptate quos.',

        priceFrom: "from",
        priceTo: "to",

        // Advert
        contactBtn: "Contact",
        sendMessageBtn: "Message",
        viewInMap: "View in Map",
        street: "street",
        description: "Description",
        detailedView: "See more",

        //Personal
        saveBtn: 'Save Changes',
        userProfilName: 'Name',
        userProfilLastName: 'LastName',
        userProfilPhone: 'Phone Number',
        userProfilPassport: 'Passport',

        //SideBar
        sMenu: `Go to home page`,
        sAdd: `Add an ad`,
        sFeatures: 'Features',
        sHelp: 'Help',
        sAds: 'Adverts',
        sLogout: 'Log Out',

        notfound: 'No pictures available',

        //Chat
        ChatNews: 'News',
        doyou: 'You might like',

        liked: `Liked`,
        err: 'Unsuccessful!!!',
        back: 'Return Back',
        confirm: 'enter the sms code you went to !!!',
        to: 'to',
        codeMessage: 'Enter SMS Code!!!',
        succ: 'Successful !!!',
        ChatNews: 'News',
        Chat: 'Seller',
        addPic: `Advert Picture`,
        doyou: 'You might like',

        liked: `Liked`,
        err: 'Unsuccessful!!!',
        back: 'Return Back',
        confirm: 'enter the sms code you went to !!!',
        to: 'to',
        codeMessage: 'Enter SMS Code!!!',
        succ: 'Successful !!!',

        noResults: "There are currently no ads posted for this request",
        changeFilterThings: "Try changing something in the filter",
        cleanFilterThings: "Try cleaning the filter",
        viaWith: "search through",
        map: "Map",

        // Search
        saleType: "Sale type",
        homeType: "Home type",
        searchPlaceholder: "Address, city, region, village, etc",
        clean: "Clean",
        viewOnMap: "View on Map",
        filter: "Filter",
        forgot: 'Forgot Password',
        forgot_title: 'Password reset',
        forgot_descr: 'Enter your email below to reset your password',
        forgot_error: 'This email address does not exist',
        forgot_title_suc: 'Successfully',
        forgot_descr_suc: 'An SMS message has been sent to the email address you entered',
        reset_pass: 'Password update',
        reset_pass_descr: 'Enter your email below to reset your password',
        form_select_pass: 'Password',
        form_select_pass_req: 'Enter new password',
        form_select_code: 'CODE',
        form_select_code_req: 'Enter the code sent to your email address',
        forgot_reset_descr: 'Your password has been successfully changed',

        //Post Edit
        edit_postTitle: 'Edit Post',
        edit_post:' chi Elon',
        edit_saleType: 'Sale Type',
        edit_houseType: 'House Type',
        edit_repairType: 'Repair condition',
        edit_materialType: 'Construction Material',
        edit_Region: 'Province',
        edit_City: 'City',
        edit_Street: 'Street',
        edit_House: 'House',
        edit_Kitchen: 'Kitchen',
        edit_Living: 'Living',
        edit_Total: 'Total',
        edit_Type: 'Total Area Type',
        edit_M2: 'Square meters',
        edit_AR: 'AR',
        edit_Date: 'Date',
        edit_Rooms: 'Rooms',
        edit_Floor: 'Floor',
        edit_Flat: 'Floors',
        edit_Video: 'Add Video',
        edit_Docs: 'Add Document',
        edit_Descr: 'Description',
        edit_Price: 'Price',
        edit_Submit: 'Affirmation',

        // Advert Tools
        advert_id:'Post ID',
        advert_areas:'square',
        advert_kitchen:'Kitchen',
        advert_living:'Residential',
        advert_total:'Total',
        advert_flat:'flat',
        advert_floor:'floor',
        advert_date:'Built year',
        advert_year:'year',
        advert_materials:'Materails',
        advert_repairs:'Repair condition',
        chat_back:'Back',

    },
    ru: {
        chat: "Чат",
        // Header
        add: "Добавить объявление",
        fromBtn: "Войти",
        placeTooltip: "Ваше местоположение",
        langTooltip: "Изменить язык",
        loveTooltip: "твои лайки",
        currencyTooltip: "обмен валюты",
        // Nav
        sal: "Продажа",
        rent: "Аренда",
        rel: "Риэлторы",
        mor: "Еще",
        // Hero
        hero_title: "Найди это. Совершите поездку. Владей этим.",
        hero_search: "Поиск",
        // Main
        nearHomes: "Ближайшие дома",
        populr_title: "Популярные дома",
        new_title: "Новые Здания",
        see_desc: "Увидеть их всех",
        reltor_aside_title: "Риэлторы",
        // Footer
        footer_text: "Национальная платформа дистанционной продажи",
        users_title: "Для пользователи",
        contact_us: "Свяжитесь с нами",
        social_networks: "Мы в социальных сетях",
        // All
        we: "Hасчет нас",
        why_afeme_title: "Почему Афеме?",
        why_afeme_bot: "AFEME BOTH AND CHANNEL",
        why_afeme_botdesc: "Попробуйте наш Telegram-бот и канал",

        // Form Modal
        form_modal_title: "Войти на сайт",
        from_modal_inputtel: "Номер телефона",
        from_modal_btnsubmit: "Войти",
        from_sign: "Зарегистрироваться",
        help: 'Помощь',

        // Form Page
        form_select_jis: "Физический",
        form_select_vil: "Oбласть",
        from_select_nam: "Имя",
        form_select_nam_req: "Введите имя",
        form_select_las: "Фамилия",
        form_select_las_req: "Введите фамилию",
        form_select_email: "Элек. почта",
        form_select_email_req: "Введите ваш адрес элек. почты",
        form_select_email_err: "Адрес элек. почты недействителен",
        form_select_pas: "Поспорт",
        form_select_tel: "Номер телефона",
        form_select_tel_req: "Введите номер телефона",
        form_myaccount: "У меня есть аккаунт",
        form_select_type_sh: 'Личный',
        form_select_type_b: 'Бизнес',
        rexperience: 'Опыт работы',
        bio: 'О себе',
        sing: 'Зарегистрироваться',
        have: 'У меня есть аккаунт',
        submit: 'Подтверждение',

        // Reltos Page
        reltor_title: "Каталог риелторов",
        reltor_lenght: "нашел риелтора",
        reltor_sort: "Сортировка",

        // User
        user_profil: "Мой профиль",
        user_profil_message: "Мои сообщения",
        user_profil_ads: "Мои объявления",
        user_profil_favorintes: "Избранное",
        user_profil_news: "Новости",
        user_profil_clos: "Выйти",

        //Help
        title: 'Помощь',
        title_descr: 'Мы всегда готовы помочь',
        name: 'Имя',
        name_error: 'Введите имя',
        number: 'Номер телефона',
        number_error: 'Пожалуйста введите ваш номер телефона !!!',
        email: 'Адрес электронной почты',
        email_error: 'Адрес электронной почты Нотогри',
        message_type: 'Тип сообщения',
        type_taklif: 'Предложение',
        type_shiqoyat: 'Жалоба',
        descr: 'Оставьте свое сообщение',
        btn: 'Отправить',

        // AdvertPage
        advert_title: "Добавить объявление",
        advert_rent: "Арендовать",
        adverd_sell: "Распродажа",
        adverd_mortgage: "Ипотека",
        adverd_build_title: "Типы зданий",
        adverd_sotish_turi: "Типы продаж",
        adverd_house: "Внутренний двор",
        adverd_office: "Офис",
        adverd_room: "Комната",
        adverd_apartment: "Квартира",
        adverd_dala: "Полевой двор",
        adverd_adres_office: "Адрес офиса",
        adverd_adres_city: "Город",
        adverd_office: "Адрес",
        adverd_house_num: "№ дома",
        adverd_about_the_office: "О офисе",
        choose: "Выбирать",
        adverd_about_1: "Год:",
        adverd_about_2: "Количество комнат:",
        adverd_about_3: "Площадь:",
        adverd_about_33: "Кухня",
        adverd_about_34: "Номер",
        adverd_about_35: "Общий",
        adverd_about_36: "Метр площади",
        adverd_about_37: "Сотих",
        adverd_about_38: "Из:",
        adverd_about_4: "Пол:",
        adverd_about_5: "Состояния:",
        adverd_about_6: "Материалы:",
        adverd_about_evro: "Yevro",
        adverd_about_normal: "O'rtacha",
        adverd_about_tiz: "Tamir talab",
        adverd_about_gsh: "G'isht",
        adverd_about_bet: "Beton",
        adverd_about_met: "Metall",
        adverd_documents: "Офисные чертежи и документы:",
        adverd_documents_dow: "Скачать документы на дом",
        adverd_office_img: "Фотографии офиса:",
        adverd_office_drop_img: "выбрать картинку",
        adverd_office_drop_video: "выбрать видео",
        adverd_office_video: "Офисные видео",
        adverd_office_textior: "Расскажи немного о доме...",
        adverd_office_price: "Цена офиса:",
        adverd_office_price_info: "Введите цену в сумме",
        adverd_submit: "Сохранить",

        afemePhoneTitle: `теперь он всегда будет в ваших руках`,
        afemePhoneDescr: 'В приложении можно управлять ЖКХ и следить за процессом: сообщаем обо всем важном.',
        partners_title: 'Наши партнеры',
        partners_descr: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laudantium ducimus in, voluptate deserunt magni fugit error atque modi iure maiores possimus nesciunt? Tempore odit ratione sunt, ut dignissimos, exercitationem a mollitia necessitatibus, aliquam asperiores neque! Quae id quod voluptate quos.',

        priceFrom: "от",
        priceTo: "до",

        // Advert
        contactBtn: "Связь",
        sendMessageBtn: "Сообщение",
        viewInMap: "Вид с карты",
        street: "Улица",
        description: "Описание",
        detailedView: "Узнать больше",

        //Personal
        saveBtn: 'Сохранить изменения',
        userProfilName: 'Имя',
        userProfilLastName: 'Фамилия',
        userProfilPhone: 'Номер телефона',
        userProfilPassport: 'Паспорт',

        //SideBar
        sMenu: `На главную страницу`,
        sAdd: `Добавить объявление`,
        sFeatures: 'Избранные',
        sHelp: 'Помощь',
        sAds: 'Oбъявление',
        sLogout: 'Выйти',

        notfound: 'Нет доступных изображений',

        //Chat
        ChatNews: 'Новости',
        doyou: 'Вам может понравиться',

        liked: `Понравилось`,
        err: 'Неудачно!!!',
        back: 'Вернуться Назад',
        confirm: 'введите код смс, на который вы зашли !!!',
        to: 'к',
        codeMessage: 'Введите смс-код!!!',
        succ: 'Успешный !!!',
        ChatNews: 'Новости',
        Chat: 'Продавец',
        addPic: `Рекламная картинка`,
        doyou: 'Вам может понравиться',

        liked: `Понравилось`,
        err: 'Неудачно!!!',
        back: 'Вернуться Назад',
        confirm: 'введите код смс, на который вы зашли !!!',
        to: 'к',
        codeMessage: 'Введите смс-код!!!',
        succ: 'Успешный !!!',

        noResults: "В настоящее время нет размещенных объявлений по этому запросу",
        changeFilterThings: "Попробуйте изменить что-то в фильтре",
        cleanFilterThings: "попробуй почистить фильтр",
        viaWith: "искать через",
        map: "Карта",

        // Search
        saleType: "Тип продажи",
        homeType: "Тип дома",
        searchPlaceholder: "Адрес, город, район, село и т.д.",
        clean: "Чистый",
        viewOnMap: "Посмотреть на карте",
        filter: "Фильтр",

        forgot: 'Забыл пароль',
        forgot_title: 'Сброс пароля',
        forgot_descr: 'Введите ниже свой адрес элек. почты, чтобы сбросить пароль',
        forgot_error: 'Этот адрес элек. почты не существует',
        forgot_title_suc: 'Успешно',
        forgot_descr_suc: 'На указанный вами адрес элек. почты отправлено SMS-сообщение',
        reset_pass: 'Обновление пароля',
        reset_pass_descr: 'Введите ниже свой адрес элек. почты, чтобы сбросить пароль',
        form_select_pass: 'Пароль',
        form_select_pass_req: 'Введите новый пароль',
        form_select_code: 'CODE',
        form_select_code_req: 'Введите код, отправленный на ваш адрес элек. почты',
        forgot_reset_descr: 'Ваш пароль был успешно изменен',

        //Post Edit
        edit_postTitle: 'Редактирование объявления',
        edit_post:'-е объявление',
        edit_saleType: 'Тип продажи',
        edit_houseType: 'Тип дома',
        edit_repairType: 'Состояние ремонта',
        edit_materialType: 'Строительный материал',
        edit_Region: 'Область',
        edit_City: 'Город',
        edit_Street: 'Улица',
        edit_House: 'Дом',
        edit_Kitchen: 'Кухня',
        edit_Living: 'Жилая',
        edit_Total: 'Общее',
        edit_Type: 'Тип общей площади',
        edit_M2: 'Kвадратных метров',
        edit_AR: 'Cотых',
        edit_Date: 'Год',
        edit_Rooms: 'Комнаты',
        edit_Floor: 'Этаж',
        edit_Flat: 'Этажность',
        edit_Video: 'Добавьте видео',
        edit_Docs: 'Добавьте документ',
        edit_Descr: 'Описание',
        edit_Price: 'Цена',
        edit_Submit: 'Подтвердить',

        // Advert Tools
        advert_id:'ID поста',
        advert_areas:'площадь',
        advert_kitchen:'кухня',
        advert_living:'жилой',
        advert_total:'oбщее',
        advert_flat:'этажность',
        advert_floor:'этаж',
        advert_date:'Год постройки',
        advert_year:'год',
        advert_materials:'Материалы',
        advert_repairs:'Состояние ремонта',
        chat_back:'Назад',
    },
}
export default content;