const content = {
    uz: {

        // Header
        add: "E'lon Qo'shish",
        fromBtn: "Kirish",
        placeTooltip: "Joylashuvingiz",
        langTooltip: "Tilni almashtirish",
        loveTooltip: "Sizning Yoqtirganlaringiz",
        currencyTooltip: "Valyutani almashtirish",

        // Navbar
        sal: "Sotuv",
        rent: "Ijara",
        rel: "Reltorlar",
        mor: "Yana",

        // Hero
        hero_title: "Toping. Sayohat qiling. Egalik qiling.",
        hero_search: "Qidirish",

        // Main
        recom_title: "Tavsiya etilgan turar-joy majmualari",
        populr_title: "Ommabop Uylar",
        new_title: "Yangi Binolar",
        see_desc: "Barchasini ko’rish",
        reltor_aside_title: "Reltorlar",
        error_desc: "Ma'lumotlar olishda xatolik yuz berdi",

        // Footer
        footer_text: "Masofaviy Uy oldi sotdisi bo'yicha Milliy platforma",
        users_title: "Foydalanuvchilarga",
        contact_us: "Biz bilan aloqa",
        social_networks: "Biz ijtimoiy tarmoqlarda",

        // Bilmadim bu nimaligni lekin
        we: "Biz haqimizda",
        why_afeme_title: "Nima uchun Afeme ?",
        why_afeme_bot: "AFEME BOTI VA KANALI",
        why_afeme_botdesc: "Telegram bot va kanalimizni ishlatib koʻring",

        // Form Modal
        form_modal_title: "Saytga kirish",
        from_modal_inputtel: "Telfon Raqam",
        from_modal_btnsubmit: "Kirish",
        from_sign: "Ro'yxatdan o'tish",
        help: 'Yordam',

        // Form Page
        form_select_jis: "Jismoniy shaxs",
        form_select_vil: "Viloyat",
        from_select_nam: "Ism",
        form_select_las: "Familiya",
        form_select_ema: "Email",
        form_select_pas: "Passport",
        form_select_tel: "Telefon raqam",
        form_myaccount: "Mening hisobim bor",
        form_select_type_sh: 'Shaxsiy',
        form_select_type_b: 'Biznez',
        rexperience: 'Tajriba',
        bio: 'Malumot',
        have: 'Mening Akkauntim bor',
        sing: 'Royhatdan otish',

        // Reltos Page
        reltor_title: "Rieltorlar katalogi",
        reltor_lenght: "ta rieltor topildi",
        reltor_sort: "Filterlash",
        no_post: "Siz birorta ham E'lon joylashtirmadingiz",

        // Errors
        apiError: "Ma'lumotlar olishda xatolik yuz berdi",
        internetError: "Internet bilan aloqa Uzildi. Internet mavjud emas",

        // User Profil
        user_profil: "Mening profilim",
        user_profil_ads: "Mening eʻlonlarim",
        user_profil_message: "Mening xabarlarim",
        user_profil_favorintes: "Tanlanganlar",
        user_profil_news: "Yangiliklar",
        user_profil_clos: "Chiqish",

        //Help
        title: 'Yordam',
        title_descr: 'Biz xardoim yordam berishga tayormiz',
        name: 'Ism',
        name_error: 'Ism Kiriting',
        number: 'Telefon Raqam',
        number_error: 'Iltimos Telefon Raqamingizni Kiriting!!!',
        email: 'Email Manzili',
        email_error: 'Email Manzili Notogri',
        message_type: 'Habar Turi',
        type_taklif: 'Taqlif',
        type_shiqoyat: 'Shiqoyat',
        descr: 'Habaringizni Koldiring',
        btn: 'Yuborish',

        // AdvertPage
        advert_title: "E'lon qo'shish",
        advert_rent: "Ijara",
        adverd_sell: "Sotuv",
        adverd_mortgage: "Ipoteka",
        adverd_build_title: "Bino Turlari",
        adverd_sotish_turi: "Sotish Turlari",
        adverd_house: "Hovli",
        adverd_office: "Ofis",
        adverd_room: "Xona",
        adverd_apartment: "Kvartira",
        adverd_dala: "Dala Hovli",
        adverd_adres_office: "Ofis manzili",
        adverd_adres_city: "Shahar",
        adverd_office: "Manzil",
        adverd_about_the_office: "Ofis Haqida",
        adverd_about_1: "Qurilgan Yili:",
        adverd_about_2: "Honalar soni:",
        adverd_about_3: "Maydoni:",
        adverd_about_33: "Oshxona",
        adverd_about_34: "Xona",
        adverd_about_35: "Jami",
        adverd_about_36: "Metr Kvadrat",
        adverd_about_37: "Sotix",
        adverd_about_38: "dan:", 
        adverd_about_4: "Qavat:",
        adverd_about_5: "Tamir holati:",
        adverd_about_6: "Materiallari:",
        adverd_about_evro: "Yevro",
        adverd_about_normal: "O'rtacha",
        adverd_about_tiz: "Tamir talab",
        adverd_about_gsh: "G'isht",
        adverd_about_bet: "Beton",
        adverd_about_met: "Metall",
        adverd_documents: "Ofis Chizmasi va Hujjatlari:",
        adverd_documents_dow: "Uy Hujjatlarini Yuklang",
        adverd_office_img: "Ofis rasmlari:",
        adverd_office_drop_img: "rasimni tanlang",
        adverd_office_drop_video: "videoni tanlang",
        adverd_office_video: "Ofis videolari",
        adverd_office_textior: "Uy hakida kiskacha malumot bering...",
        adverd_office_price: "Ofis narxi:",
        adverd_office_price_info: "Narxni kiriting somda",
        adverd_submit: "Elonni Yuklash",

        afemePhoneTitle: `endi har doim qo'lingizda`,
        afemePhoneDescr: 'Ilovada siz uy-joy kommunal xizmatlarini boshqarishingiz va jarayonni kuzatishingiz mumkin Biz barcha muhim narsalarni xabar qilamiz.',
        partners_title: 'Bizning hamkorlar',
        partners_descr: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laudantium ducimus in, voluptate deserunt magni fugit error atque modi iure maiores possimus nesciunt? Tempore odit ratione sunt, ut dignissimos, exercitationem a mollitia necessitatibus, aliquam asperiores neque! Quae id quod voluptate quos.',

        priceFrom: "dan",
        priceTo: "gacha",

        chat: "Chat",

        // Advert
        contactBtn: "Bog'lanish",
        sendMessageBtn: "Xabar yozish",
        viewInMap: "Kartadan ko'rish",
        street: "ko'chasi",
        description: "Tavsif",
        detailedView: "Batafsil ko'rish",

        //Personal
        editBtn: 'Tahrirlash',
        userProfilName:'Ism',
        userProfilLastName:'Familiya',
        userProfilPhone:'Telefon Raqami',
        userProfilPassport:'Passport',

        //SideBar
        sMenu:`Bosh sahifaga o'tish`,
        sAdd:`E'lon qo'shish`,
        sFeatures:'Tanlanganlar',
        sHelp:'Yordam',
        sAbout:'Biz haqimizda',
        sLogout:'Chiqish',

        notfound:'Rasmlar mavjud emas',

        //Chat
        ChatNews:'Xabarlar',
        Chat:'Sotuvchi',
        addPic:`E'lon Rasmi`,
        doyou:'Sizga yoqishi mumkin',

        liked:`Yoqtirganlarga qo'shish`,
        err:'Muvaffaqiyatsiz !!!',
        back:'Ortga Kaytish',
        confirm:'borgan sms kodni kiriting !!!',
        to:'ga',
        codeMessage:'Sms Kodni kiring!!!',
        succ:'Muvaffaqiyatli !!!',

        noResults: "Hozircha bu so'rov bo'yicha hech qanday e'lon qo'yilmagan",
        changeFilterThings: "Filterda biror narsani o'zgartirib ko'ring",
        cleanFilterThings: "Filterni tozalashga harakat qilib ko'ring",
        viaWith: "orqali qidiring",
        map: "Xarita"
    },
    en: {
        chat: "Chat",
        // Header
        add: "Add an ad",
        fromBtn: "Sign in",
        placeTooltip: "Your location",
        langTooltip: "Change language",
        loveTooltip: "Your likes",
        currencyTooltip: "Change currency",
        // Nav
        sal: "Sales",
        rent: "Rent",
        rel: "Realtors",
        mor: "More",
        // Hero
        hero_title: "Find it. Tour it. Own it.",
        hero_search: "Search",
        // Main
        recom_title: "Recommended residential complexes",
        populr_title: "Popular Houses",
        new_title: "New Buildings",
        see_desc: "See more",
        reltor_aside_title: "Realtors",
        // Footer
        footer_text: "National Platform for Remote Sale",
        users_title: "Users",
        contact_us: "Contact us",
        social_networks: "We are on social media",

        we: "About Us",
        why_afeme_title: "Why Afeme ?",
        why_afeme_bot: "AFEME TELEGRAM BOT AND CHANNEL",
        why_afeme_botdesc: "Try our Telegram bot and channel",

        // Form Modal
        form_modal_title: "Sign in",
        from_modal_inputtel: "Phone number",
        from_modal_btnsubmit: "Get started",
        from_sign: "Register",
        help: 'Help',

        // Form Page
        form_select_jis: "Individual",
        form_select_vil: "Province",
        from_select_nam: "Name",
        form_select_las: "Surname",
        form_select_ema: "Email",
        form_select_pas: "Passport",
        form_select_tel: "Phone number",
        form_myaccount: "I have an account",
        form_select_type_sh: 'Personal',
        form_select_type_b: 'Bussines',
        rexperience: 'Experience',
        bio: 'About your self',
        have: 'I have an account',
        sing: 'SingUp',

        // Reltos Page
        reltor_title: "Directory of Realtors",
        reltor_lenght: "founded this Realtors",
        reltor_sort: "Sorting",

        // User
        user_profil: "My profile",
        user_profil_message: "My Messages",
        user_profil_ads: "My listings",
        user_profil_favorintes: "Favorites",
        user_profil_news: "News",
        user_profil_clos: "Logout",

        //Help
        title: 'Help',
        title_descr: 'We are always ready to help',
        name: 'Name',
        name_error: 'Enter a name',
        number: 'Telephone Number',
        number_error: 'Enter a number',
        email: 'Email',
        email_error: 'Email address Incorrect',
        message_type: 'Message Type',
        type_taklif: 'Offer',
        type_shiqoyat: 'Complaint',
        descr: 'Leave your message',
        btn: 'Send',

        // AdvertPage
        advert_title: "Add an ad",
        advert_rent: "Rent",
        adverd_sell: "Sale",
        adverd_mortgage: "Mortgage",
        adverd_build_title: "Building Types",
        adverd_sotish_turi: "Sales Types",
        adverd_house: "Courtyard",
        adverd_office: "Office",
        adverd_room: "Room",
        adverd_apartment: "Apartment",
        adverd_dala: "Field Yard",
        adverd_adres_office: "Office address",
        adverd_adres_city: "City",
        adverd_office: "Address",
        adverd_about_the_office: "About the office",
        adverd_about_1: "Built Year:",
        adverd_about_2: "Number of rooms:",
        adverd_about_3: "Area:",
        adverd_about_33: "Kitchen",
        adverd_about_34: "Room",
        adverd_about_35: "Total",
        adverd_about_36: "Meter Square",
        adverd_about_37: "Sotikh",
        adverd_about_38: "from:", 
        adverd_about_4: "Floor:",
        adverd_about_5: "Repair status:",
        adverd_about_6: "Materials:",
        adverd_about_evro: "EUR",
        adverd_about_normal: "O'rtacha",
        adverd_about_tiz: "Tamir talab",
        adverd_about_gsh: "G'isht",
        adverd_about_bet: "Beton",
        adverd_about_met: "Metall",
        adverd_documents: "Office Drawings and Documents:",
        adverd_documents_dow: "Download House Documents",
        adverd_office_img: "Office pictures:",
        adverd_office_drop_img: "select a picture",
        adverd_office_drop_video: "select a video",
        adverd_office_video: "Office videos",
        adverd_office_textior: "Tell me a little about the house...",
        adverd_office_price: "Office price:",
        adverd_office_price_info: "Enter the price in sum",
        adverd_submit: "Save",

        afemePhoneTitle: `now it will always be in your hands`,
        afemePhoneDescr: 'In the app, you can manage housing utilities and monitor the process: we report all the important things.',
        partners_title: 'Our partners',
        partners_descr: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laudantium ducimus in, voluptate deserunt magni fugit error atque modi iure maiores possimus nesciunt? Tempore odit ratione sunt, ut dignissimos, exercitationem a mollitia necessitatibus, aliquam asperiores neque! Quae id quod voluptate quos.',

        priceFrom: "from",
        priceTo: "to",

        // Advert
        contactBtn: "Contact",
        sendMessageBtn: "Message",
        viewInMap: "View in Map",
        street: "street",
        description: "Description",
        detailedView: "See more",

        //Personal
        editBtn: 'Edit',
        userProfilName:'Name',
        userProfilLastName:'LastName',
        userProfilPhone:'Phone Number',
        userProfilPassport:'Passport',

        //SideBar
        sMenu:`Go to home page`,
        sAdd:`Add an ad`,
        sFeatures:'Features',
        sHelp:'Help',
        sAbout:'About',
        sLogout:'Log Out',

        notfound:'No pictures available',

        //Chat
        ChatNews:'News',
        Chat:'Seller',
        addPic:`Advert Picture`,
        doyou:'You might like',

        liked:`Liked`,
        err:'Unsuccessful!!!',
        back:'Return Back',
        confirm:'enter the sms code you went to !!!',
        to:'to',
        codeMessage:'Enter SMS Code!!!',
        succ:'Successful !!!',

        noResults: "There are currently no ads posted for this request",
        changeFilterThings: "Try changing something in the filter",
        cleanFilterThings: "Try cleaning the filter",
        viaWith: "search through",
        map: "Map"
    },
    ru: {
        chat: "Чат",
        // Header
        add: "Добавить объявление",
        fromBtn: "Войти",
        placeTooltip: "Ваше местоположение",
        langTooltip: "Изменить язык",
        loveTooltip: "твои лайки",
        currencyTooltip: "обмен валюты",
        // Nav
        sal: "Продажа",
        rent: "Аренда",
        rel: "Риэлторы",
        mor: "Еще",
        // Hero
        hero_title: "Найди это. Совершите поездку. Владей этим.",
        hero_search: "Поиск",
        // Main
        recom_title: "Рекомендуемые жилые комплексы",
        populr_title: "Популярные дома",
        new_title: "Новые Здания",
        see_desc: "Увидеть их всех",
        reltor_aside_title: "Риэлторы",
        // Footer
        footer_text: "Национальная платформа дистанционной продажи",
        users_title: "Для пользователи",
        contact_us: "Свяжитесь с нами",
        social_networks: "Мы в социальных сетях",
        // All
        we: "Hасчет нас",
        why_afeme_title: "Почему Афеме?",
        why_afeme_bot: "AFEME BOTH AND CHANNEL",
        why_afeme_botdesc: "Попробуйте наш Telegram-бот и канал",

        // Form Modal
        form_modal_title: "Войти на сайт",
        from_modal_inputtel: "Номер телефона",
        from_modal_btnsubmit: "Войти",
        from_sign: "Зарегистрироваться",
        help: 'Помощь',

        // Form Page
        form_select_jis: "Физический",
        form_select_vil: "Провинция",
        from_select_nam: "Имя",
        form_select_las: "Фамилия",
        form_select_ema: "Эл. адрес",
        form_select_pas: "Поспорт",
        form_select_tel: "Номер телефона",
        form_myaccount: "У меня есть аккаунт",
        form_select_type_sh: 'Личный',
        form_select_type_b: 'Бизнес',
        rexperience: 'Опыт работы',
        bio: 'О себе',
        sing: 'Зарегистрироваться',
        have: 'У меня есть аккаунт',

        // Reltos Page
        reltor_title: "Каталог риелторов",
        reltor_lenght: "нашел риелтора",
        reltor_sort: "Сортировка",

        // User
        user_profil: "Мой профиль",
        user_profil_message: "Мои сообщения",
        user_profil_ads: "Мои объявления",
        user_profil_favorintes: "Избранное",
        user_profil_news: "Новости",
        user_profil_clos: "Выйти",

        //Help
        title: 'Помощь',
        title_descr: 'Мы всегда готовы помочь',
        name: 'Имя',
        name_error: 'Введите имя',
        number: 'Номер телефона',
        number_error: 'Пожалуйста введите ваш номер телефона !!!',
        email: 'Адрес электронной почты',
        email_error: 'Адрес электронной почты Нотогри',
        message_type: 'Тип сообщения',
        type_taklif: 'Предложение',
        type_shiqoyat: 'Жалоба',
        descr: 'Оставьте свое сообщение',
        btn: 'Отправить',

        // AdvertPage
        advert_title: "Добавить объявление",
        advert_rent: "Арендовать",
        adverd_sell: "Распродажа",
        adverd_mortgage: "Ипотека",
        adverd_build_title: "Типы зданий",
        adverd_sotish_turi: "Типы продаж",
        adverd_house: "Внутренний двор",
        adverd_office: "Офис",
        adverd_room: "Комната",
        adverd_apartment: "Квартира",
        adverd_dala: "Полевой двор",
        adverd_adres_office: "Адрес офиса",
        adverd_adres_city: "Город",
        adverd_office: "Адрес",
        adverd_about_the_office: "О офисе",
        adverd_about_1: "Год постройки:",
        adverd_about_2: "Количество комнат:",
        adverd_about_3: "Область:",
        adverd_about_33: "Кухня",
        adverd_about_34: "Номер",
        adverd_about_35: "Общий",
        adverd_about_36: "Метр площади",
        adverd_about_37: "Сотих",
        adverd_about_38: "Из:", 
        adverd_about_4: "Пол:",
        adverd_about_5: "Статус ремонта:",
        adverd_about_6: "Материалы:",
        adverd_about_evro: "Yevro",
        adverd_about_normal: "O'rtacha",
        adverd_about_tiz: "Tamir talab",
        adverd_about_gsh: "G'isht",
        adverd_about_bet: "Beton",
        adverd_about_met: "Metall",
        adverd_documents: "Офисные чертежи и документы:",
        adverd_documents_dow: "Скачать документы на дом",
        adverd_office_img: "Фотографии офиса:",
        adverd_office_drop_img: "выбрать картинку",
        adverd_office_drop_video: "выбрать видео",
        adverd_office_video: "Офисные видео",
        adverd_office_textior: "Расскажи немного о доме...",
        adverd_office_price: "Цена офиса:",
        adverd_office_price_info: "Введите цену в сумме",
        adverd_submit: "Сохранить",

        afemePhoneTitle: `теперь он всегда будет в ваших руках`,
        afemePhoneDescr: 'В приложении можно управлять ЖКХ и следить за процессом: сообщаем обо всем важном.',
        partners_title: 'Наши партнеры',
        partners_descr: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laudantium ducimus in, voluptate deserunt magni fugit error atque modi iure maiores possimus nesciunt? Tempore odit ratione sunt, ut dignissimos, exercitationem a mollitia necessitatibus, aliquam asperiores neque! Quae id quod voluptate quos.',

        priceFrom: "от",
        priceTo: "до",

        // Advert
        contactBtn: "Связь",
        sendMessageBtn: "Сообщение",
        viewInMap: "Вид с карты",
        street: "Улица",
        description: "Описание",
        detailedView: "Узнать больше",

        //Personal
        editBtn: 'Изменить',
        userProfilName:'Имя',
        userProfilLastName:'Фамилия',
        userProfilPhone:'Номер телефона',
        userProfilPassport:'Паспорт',

        //SideBar
        sMenu:`На главную страницу`,
        sAdd:`Добавить объявление`,
        sFeatures:'Избранные',
        sHelp:'Помощь',
        sAbout:'О компании',
        sLogout:'Выйти',

        notfound:'Нет доступных изображений',

        //Chat
        ChatNews:'Новости',
        Chat:'Продавец',
        addPic:`Рекламная картинка`,
        doyou:'Вам может понравиться',

        liked:`Понравилось`,
        err:'Неудачно!!!',
        back:'Вернуться Назад',
        confirm:'введите код смс, на который вы зашли !!!',
        to:'к',
        codeMessage:'Введите смс-код!!!',
        succ:'Успешный !!!',

        noResults: "В настоящее время нет размещенных объявлений по этому запросу",
        changeFilterThings: "Попробуйте изменить что-то в фильтре",
        cleanFilterThings: "попробуй почистить фильтр",
        viaWith: "искать через",
        map: "Карта",
    }
}
export default content;